// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/shippy-service-consignment.proto

package shippyserviceconsignment

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ShippyServiceConsignment service

func NewShippyServiceConsignmentEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ShippyServiceConsignment service

type ShippyServiceConsignmentService interface {
	CreateConsignment(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error)
}

type shippyServiceConsignmentService struct {
	c    client.Client
	name string
}

func NewShippyServiceConsignmentService(name string, c client.Client) ShippyServiceConsignmentService {
	return &shippyServiceConsignmentService{
		c:    c,
		name: name,
	}
}

func (c *shippyServiceConsignmentService) CreateConsignment(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ShippyServiceConsignment.CreateConsignment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShippyServiceConsignment service

type ShippyServiceConsignmentHandler interface {
	CreateConsignment(context.Context, *Consignment, *Response) error
}

func RegisterShippyServiceConsignmentHandler(s server.Server, hdlr ShippyServiceConsignmentHandler, opts ...server.HandlerOption) error {
	type shippyServiceConsignment interface {
		CreateConsignment(ctx context.Context, in *Consignment, out *Response) error
	}
	type ShippyServiceConsignment struct {
		shippyServiceConsignment
	}
	h := &shippyServiceConsignmentHandler{hdlr}
	return s.Handle(s.NewHandler(&ShippyServiceConsignment{h}, opts...))
}

type shippyServiceConsignmentHandler struct {
	ShippyServiceConsignmentHandler
}

func (h *shippyServiceConsignmentHandler) CreateConsignment(ctx context.Context, in *Consignment, out *Response) error {
	return h.ShippyServiceConsignmentHandler.CreateConsignment(ctx, in, out)
}
